# Generated by Django 5.0.1 on 2024-02-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_producto_precio_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(max_length=50),
        ),
    ]
