# Generated by Django 5.0.1 on 2024-02-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_producto_stock_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(),
        ),
    ]
