# Generated by Django 5.0.1 on 2024-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_producto_stock_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.IntegerField(),
        ),
    ]
